#!/bin/bash

PS3='Enter your choice : '
options=("Option 1" "Option 2" "Option 3" "Quit")

select opt in "${options[@]}"
do
case $opt in
	"Option 1")
		echo "You have selected Option 1"
		;;
	"Option 2")
                echo "You have selected Option 2"
                ;;
	"Option 3")
                echo "You have selected $REPLY with $opt"
                ;;
	"Quit")
		break
		;;
	*) echo "Invalid option $REPLY" ;;
esac
done

